
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fondak_development
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fondak_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fondak
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock